In [4]:
pip install scikit-fuzzy

Collecting scikit-fuzzyNote: you may need to restart the kernel to use updated packages.

  Downloading scikit-fuzzy-0.4.2.tar.gz (993 kB)
     -------------------------------------- 994.0/994.0 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.6.0 in c:\users\shine\anaconda3\envs\environment\lib\site-packages (from scikit-fuzzy) (1.22.4)
Requirement already satisfied: scipy>=0.9.0 in c:\users\shine\anaconda3\envs\environment\lib\site-packages (from scikit-fuzzy) (1.7.3)
Requirement already satisfied: networkx>=1.9.0 in c:\users\shine\anaconda3\envs\environment\lib\site-packages (from scikit-fuzzy) (2.8.4)
Building wheels for collected packages: scikit-fuzzy
  Building wheel for scikit-fuzzy (setup.py): started
  Building wheel for scikit-fuzzy (setup.py): finished with status 'done'
  Created wheel for scikit-fuzzy: filename=scikit_fuzzy-0.4.2-py3-none-any.whl size=894075 sha256=53fdb4241e24e461deb2b738e746f9c61d73c25b15cce053fbdb457e7622955c
  Stored in directory: c:\users\shine\appdata\local\pip\cache\wheels\32\2c\a1\a90a7d7dd8448ec029f298a61f3490275e99b17aa348be675c
Successfully built scikit-fuzzy
Installing collected packages: scikit-fuzzy
Successfully installed scikit-fuzzy-0.4.2

In [1]:
import numpy as np
import copy
import tensorflow as tf
from sklearn import preprocessing
from tensorflow import keras
import os
import pandas as pd
import matplotlib.pyplot as plt
from numpy.random import seed
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

In [2]:
np.random.seed(1)
data=pd.read_csv(r"rainfall_data.csv")

In [5]:
import skfuzzy as fuzz

# Define the number of output levels (discretization levels)
num_levels = 5

# Generate membership functions for each level
levels = np.arange(num_levels)
mf = [fuzz.trimf(levels, [i-1, i, i+1]) for i in levels]

# Apply fuzzy membership function to the data
fuzzy_membership = [fuzz.interp_membership(levels, m, data["windspeed"]) for m in mf]

# Assign discretization levels based on the highest membership value
discretized = np.argmax(fuzzy_membership, axis=0)

# Add the discretized column to the dataframe
data["windspeed_discretized"] = discretized

In [6]:
data

           date  windspeed       tpw   rainfall  windspeed_discretized
0      6/1/2000  12.245595  0.033285   4.688589                      0
1      6/2/2000  12.825491  0.044874  11.330589                      0
2      6/3/2000  12.921664  0.010243   6.894713                      0
3      6/4/2000  15.149001  0.036881   4.613324                      0
4      6/5/2000  18.495907  0.139491   8.111635                      0
...         ...        ...       ...        ...                    ...
2557  9/26/2020   5.577215  0.009963   4.467977                      0
2558  9/27/2020   5.184293  0.002341   1.572182                      0
2559  9/28/2020   4.469007  0.000867   1.819019                      0
2560  9/29/2020   4.259090  0.001416   2.198017                      0
2561  9/30/2020   5.513838  0.002474  12.713634                      0

[2562 rows x 5 columns]

In [13]:
unique_ = data['rainfall_discretized'].unique()
print(unique_)

[0 4 3 1 2]

In [10]:
import skfuzzy as fuzz

# Define the number of output levels (discretization levels)
num_levels = 5

# Generate membership functions for each variable and level
tpw_levels = np.arange(num_levels)
tpw_mf = [fuzz.trimf(tpw_levels, [i-1, i, i+1]) for i in tpw_levels]

rainfall_levels = np.arange(num_levels)
rainfall_mf = [fuzz.trimf(rainfall_levels, [i-1, i, i+1]) for i in rainfall_levels]

windspeed_levels = np.arange(num_levels)
windspeed_mf = [fuzz.trimf(windspeed_levels, [i-1, i, i+1]) for i in windspeed_levels]

# Apply fuzzy membership function to the data
tpw_fuzzy_membership = [fuzz.interp_membership(tpw_levels, m, data["tpw"]) for m in tpw_mf]
rainfall_fuzzy_membership = [fuzz.interp_membership(rainfall_levels, m, data["rainfall"]) for m in rainfall_mf]
windspeed_fuzzy_membership = [fuzz.interp_membership(windspeed_levels, m, data["windspeed"]) for m in windspeed_mf]

# Assign discretization levels based on the highest membership value
tpw_discretized = np.argmax(tpw_fuzzy_membership, axis=0)
rainfall_discretized = np.argmax(rainfall_fuzzy_membership, axis =0)
windspeed_discretized =np.argmax(windspeed_fuzzy_membership ,axis=0)

# Add the discretized column to the dataframe
data["windspeed_discretized"] = windspeed_discretized
data["tpw_discretized"] = tpw_discretized
data["rainfall_discretized"] = rainfall_discretized

In [11]:
data

,date,windspeed,tpw,rainfall,windspeed_discretized,tpw_discretized,rainfall_discretized
0,6/1/2000,12.245595,0.033285,4.688589,0,0,0
1,6/2/2000,12.825491,0.044874,11.330589,0,0,0
2,6/3/2000,12.921664,0.010243,6.894713,0,0,0
3,6/4/2000,15.149001,0.036881,4.613324,0,0,0
4,6/5/2000,18.495907,0.139491,8.111635,0,0,0
...,...,...,...,...,...,...,...
2557,9/26/2020,5.577215,0.009963,4.467977,0,0,0
2558,9/27/2020,5.184293,0.002341,1.572182,0,0,2
2559,9/28/2020,4.469007,0.000867,1.819019,0,0,2
2560,9/29/2020,4.259090,0.001416,2.198017,0,0,2
2561,9/30/2020,5.513838,0.002474,12.713634,0,0,0